### ISSUE TITLE
Error Retrieving List View Objects - when user language is Hebrew

### ISSUE THREAD

**Issue by danifin** [tomansley/SimpliListViews#24] opened 2021-09-23 06:05 UTC
![image](https://user-images.githubusercontent.com/11889027/134461029-a01c1612-d193-40fa-a9ae-be2ce10bd6a2.png)
when i switch the user language to Hebrew i get the error above

**Comment by tomansley** [comment] 2021-09-24 19:39
Hello,

The app is currently only specified as being for English. But, let me see if I can figure out what is going on. Hopefully it will not be a huge deal to resolved.

Cheers
Tom

**Comment by tomansley** [comment] 2021-10-01 21:14
Hello,

This issue has been resolved and will be available in the next version which should be getting released in the next day or so.

Thanks
Tom

**Comment by danifin** [comment] 2021-10-03 06:58
Hi @tomansley,
after upgrading the package still gett the same error

**Comment by tomansley** [comment] 2021-10-03 11:33
Hello,

Thanks for letting me know.

I had Koreans that had what appeared to be the exact same problem and the
Korean language is available for me to select for the user so I used that
for testing.

How do you select Hebrew as a language in Salesforce? I do not see it as an
option. Once I am able to test in Hebrew I should hopefully be able to
resolve this issue for you.

Thanks
Tom

**Comment by danifin** [comment] 2021-10-03 11:40
i tried also Spanish and other languages and got the error
here is how you add other languages
![image](https://user-images.githubusercontent.com/11889027/135752001-12a34105-6b7a-41d9-8df4-9deadbaa69c3.png)

**Comment by tomansley** [comment] 2021-10-03 11:42
Does it work for you in Korean? If not then try do a fresh install rather than an upgrade as maybe something got stuck in the upgrade as we know Korean works. 


On Oct 3, 2021 06:40, Dani ***@***.***> wrote: 

i tried also Spanish and other languages and got the error
here is how you add other languages
 

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by danifin** [comment] 2021-10-03 13:16
i uninstalled the packed an installed again but got the same error, in 2 different orgs

**Comment by tomansley** [comment] 2021-10-03 15:49
I really appreciate you checking on this. Looks like an issue still on my
side.

Now that I know how to change to Hebrew I should be able to reproduce.

**Comment by tomansley** [comment] 2021-10-04 13:51
This issue is now resolved. I will release a new package today. Attached is a screenshot of my user using Hebrew which will hopefully give us some confidence this is resolved.

![image](https://user-images.githubusercontent.com/375321/135863347-5e6050f7-6317-4e62-8c9d-44f277eb71f8.png)

**Comment by tomansley** [comment] 2021-10-04 14:22
This change has been released on the appexchange - https://appexchange.salesforce.com/appxListingDetail?listingId=a0N3A00000FZ7BDUA1

**Closed by tomansley** 2021-10-04 14:22 UTC
Labels: bug

**Comment by danifin** [comment] 2021-10-05 05:45
thank you @tomansley !! 
it's working now
