### ISSUE TITLE
Unable to scroll conditional highlights

### ISSUE THREAD

**Issue by reachlauraanne** [tomansley/SimpliListViews#159] opened 2024-10-22 03:44 UTC
**Describe the bug**
When setting up or editing a list view and adding conditions to highlight specific fields, once the screen is filled you cannot scroll down to continue adding more.  If you zoom out it then shows room and you can add more, but you can't scroll through to the bottom.

**Simpli List View Version**
What version of SLV is currently being used? 2.306

**To Reproduce**
1. Open Simpli List Views Examples
2. Go to Everything Example
3. Click on the settings cog
4. Click on conditional highlighting
5. See error if a large number of rules are already there, otherwise create rules until the problem shows (around 13-14 rules)

**Expected behavior**
Ability to scroll or use a sliding bar on the side to go to the bottom where more can be added, like the settings page

**Screenshots**
![Conditional Formatting Issues](https://github.com/user-attachments/assets/31ae5b23-a276-4dd9-bf7b-744f1818e307)

**Desktop (please complete the following information):**
 - Browser - Chrome (same issue in Microsoft Edge)

**Comment by tomansley** [comment] 2024-10-22 11:47
Thank you for reaching out about this issue. I am surprised I forgot to
ensure the section could scroll!

This is an easy fix. I will let you know when it is resolved and available
in the app exchange.

If the issue is holding you up let me know and I will send an install link
with the fix once done.

**Comment by tomansley** [comment] 2024-10-22 12:23
This issue is resolved and will be in the next release. Here is the latest release link for your convenience - https://<YOUR_URL>/packaging/installPackage.apexp?p0=04tKY000000kZye

**Comment by reachlauraanne** [comment] 2024-10-22 23:15
Thankyou so much for your quick response and fix, this has worked perfectly

**Closed** 2024-10-22 23:15 UTC
Labels: bug, resolved, ready for release
