### ISSUE TITLE
Error Retrieving Object List Views- Value exceed maximum size limit (100KB)l 105.6KB 105.6% of limit

### ISSUE THREAD

**Issue by Keith-Colman** [tomansley/SimpliListViews#147] opened 2023-05-20 17:31 UTC
**Describe the bug**
Just installed in partial sandbox.  Opened up the Everything Example. I can see account and contact list views but when selecting "Case" in the drop down list at cases I get the error in the subject and in the attached image

**Simpli List View Version**
What version of SLV is currently being used?
2.150

**To Reproduce**
1. New Install in partial sandbox
2. Goto Everything Example
3. Select "Case" as the object

**Expected behavior**
I expect to see case list views, not an error

**Screenshots**
Attached

**Desktop (please complete the following information):**
 Windows 11, Chrome.

**Additional context**
![2023-05-20 (b)](https://github.com/tomansley/SimpliListViews/assets/134161301/6ed018f0-b8c9-464b-a4ad-083f08309d43)

**Comment by tomansley** [comment] 2023-05-23 16:05
Ok, I think you might have nailed it. There are 345 case list views. But, I
don't feel SLV should have too much of a problem handling that number.

Let me take a look at the code and see why its falling over. As a
workaround for the moment if you were able to reduce that number (I am not
completely sure by how much) it should start working again.

I'll get back to you.

**Comment by tomansley** [comment] 2023-05-23 16:13
If your org uses *Groups *then more than likely it is automatically
creating list views for those groups......which are never used.

You might want to start there.

**Comment by Keith-Colman** [comment] 2023-06-03 14:12
Hi,

Did you get a chance to look at the code yet?

Keith Colman

**Comment by tomansley** [comment] 2023-06-27 21:24
Keith,

See the latest here - https://drive.google.com/file/d/1Jz5ZJj4yM-OexrfPgd_I9KEkRAnpLHsS/view?usp=sharing

I am working on the problem but not able to reproduce right now.

Cheers
Tom

**Comment by Keith-Colman** [comment] 2023-06-28 10:42
Hi Tom,

Thanks for the update.  Appreciate the time you have spent on this.  I'll look to see if the problem exists in one of our developer sandboxes and see if I can give you access to it to debug.  We have over 650 users and are consolidating hundreds more Zendesk users into salesforce (which is where my effort if focused currently) so the number of list views is only going to increase.  Maybe its not so much the number of list views but their complexity that is causing the problem.

Regards,

Keith Colman

**Comment by tomansley** [comment] 2023-06-28 11:00
Keith,

Thanks for the patience.

I am interested in understanding this as I know there are orgs with many more users using SLV without issue.

Perhaps the list views are more complex but I don't think that's the issue as I only bring in the list view data and metadata when a user selects one.

Either way, I would really like to get you squared away and using the app so I'll keep working this on my end.

Will keep you posted.

Cheers
Tom
________________________________

**Comment by tomansley** [comment] 2023-06-28 14:42
Keith,

If you can, install the following into a sandbox and see if it solves anything - 

[https://<YOUR INSTANCE>/packaging/installPackage.apexp?p0=04t3h000004VaXe](javascript:srcUp('https%3A%2F%2F<YOUR INSTANCE>%2Fpackaging%2FinstallPackage.apexp%3Fp0%3D04t3h000004VaXe%26isdtp%3Dp1');)

I have forced the number of list views displayed to be a max of 300. It cuts off the remainder. It's not optimal for business but it would at least allow us to see if this is the problem or whether its something else.

If this works then I might need to alter how list views are selected by the user by adding in the ability to type the list view name instead of putting them all into a list.

Let me know how it goes.

Cheers
Tom

**Comment by tomansley** [comment] 2023-06-28 14:42
URL got screwed up. Try this -

https://YOUR_INSTANCE/packaging/installPackage.apexp?p0=04t3h000004VaXe

**Comment by tomansley** [comment] 2023-06-28 20:53
Keith,

Watch this - https://drive.google.com/file/d/1keZ0T4PV2a18FGksiG00iB3aqmgwuYMV/view?usp=sharing

And if you think the solution will work for you then install this into a sandbox - 

https://<YOUR_INSTANCE>/packaging/installPackage.apexp?p0=04t3h000004pOKX

Let me know your thoughts once you have had time to install.

Cheers
Tom

**Comment by Keith-Colman** [comment] 2023-06-29 21:06
Thanks for this Tom.  I'll give it a try next week.  Like you I'm a little bogged down presently with another Zendesk migrations.

Keith

**Comment by Keith-Colman** [comment] 2023-07-10 12:21
Hi Tom,

I installed this and the fix works.  I left the feature turned off and the problem was still there, I then turned it on and all was well.  Just testing it now in sandbox and getting to know the product before deploying it in production.

Thanks

Keith Colman

**Comment by tomansley** [comment] 2023-07-10 13:42
Excellent news.

I will look at getting an official release out in the next week or so and
include this change.

**Comment by tomansley** [comment] 2023-07-12 17:23
Fix released in v 2.155

**Closed by tomansley** 2023-07-12 17:23 UTC
