### ISSUE TITLE
Error On Page Load in Multiple List View Mode

### ISSUE THREAD

**Issue by geekyakshay** [tomansley/SimpliListViews#76] opened 2021-12-17 14:14 UTC
**Describe the bug**
We have two SIMPLI List Views configured on the account record page. 
A - Related List View
B - Single List View

List View B is expecting a selection of rows in List View A. But since on a page load, no selection is present in List View A, List View B is throwing an exception.

**Simpli List View Version**
v2.83

**To Reproduce**
1. Go to the Account record page, edit the lighting page.
2. Drag-drop simpliUiListViews on the page, Configure it to display any parent object records.
4. Again, Drag-drop simpliUiListViews on the page, Configure it to display child object records. Specify the API name of the field in 'Joined Field Name' during component configuration, which will link the child to its parent object. This is to filter the child records on the selection of parent records.
5. Save the lightning page.
6. Observe exceptions thrown during run time.

**Expected behavior**

**Screenshots**
Exception:
![image](https://user-images.githubusercontent.com/33083757/146556831-71cfc67f-0168-401a-a313-43175826d5d7.png)
Console:
![image](https://user-images.githubusercontent.com/33083757/146557167-0d69f84f-a277-49e9-89bc-1bde5f72c53a.png)
![image](https://user-images.githubusercontent.com/33083757/146557190-16c35462-724d-4c64-90b3-f39c7089e60e.png)

**Desktop (please complete the following information):**
 Chrome - Version 96.0.4664.110 (Official Build) (64-bit)

**Additional context**
The similar issue is not observed in your three component list view example page.

**Comment by tomansley** [comment] 2021-12-17 14:27
Hello,

Thank you so much for the awesome screenshots and information. It is much appreciated and helps immensely.

I have a question. I see the pageName in the console logs is "My_Component_Name". Do both components happen to have the same name? If so does it make a difference if the names are different?

Cheers
Tom

**Comment by geekyakshay** [comment] 2021-12-17 14:32
Thanks, Just trying to be more technical to help you resolve the issue faster. :)
Tried changing the component names for both the lists, Still the same issue.

**Comment by tomansley** [comment] 2021-12-17 14:34
It helps....alot!

Ok perfect. I am trying to reproduce now. Hopefully I can get this resolved
and released soon.

**Comment by geekyakshay** [comment] 2021-12-17 14:42
@tomansley  Additional Info:
On a record page, we have configured to filter the parent list view record using the 'Joined Field Name' configuration.
Example: Account Rec Page - Parent List Component Configuration below:
List View API Name - All_Accounts
Joined Field Name - Id
![image](https://user-images.githubusercontent.com/33083757/146561227-81e940e3-76a9-43eb-9d95-e2f0e5d4fd38.png)

Child List Component Configuration below:
List View API Name - AllContacts
Joined Field Name - AccountId
![image](https://user-images.githubusercontent.com/33083757/146561332-a73d0be7-da27-428d-a85e-dccfd4d66478.png)

**Comment by tomansley** [comment] 2021-12-17 15:00
Akshay,

I am struggling to reproduce. But, I created a release which checks for no data. It's not an official release but install the version below and let me know if it resolves your issue. If not I might need screenshots of how your components look. Perhaps I am confused.

https://<YOUR_URL>/packaging/installPackage.apexp?p0=04t3h000004pMtb

It might take a few minutes to be available.

**Comment by tomansley** [comment] 2021-12-17 15:06
One other thought. Are you absolutely sure the list view you have specified to display is correct? It needs to be the API name of the list view.

![image](https://user-images.githubusercontent.com/375321/146564567-75b11a92-2f89-4016-81d4-2bb984575f92.png)

You can verify that it is correct by looking in the list view table.

![image](https://user-images.githubusercontent.com/375321/146564884-b01baeca-9d9f-4997-83f5-6a5a748d81fc.png)

**Comment by geekyakshay** [comment] 2021-12-17 15:24
Installed your non-release version in test org and seems like the component altogether stopped working. Its not loading data anywhere. Note: I have refreshed list views already.
![image](https://user-images.githubusercontent.com/33083757/146567330-207f8a7f-18f2-4436-bb11-517ce8e2d9b4.png)

Console Log: 
`ea-dev-org-dev-ed.my.salesforce.com/one/null:1 Failed to load resource: the server responded with a status of 404 (Not Found)
​ Starting simpliUIListViews.renderedCallback
​ Record id - undefined
​ Starting simpliUIListViewsStart.renderedCallback for undefined
​ Get Component Descriptions called successfully - [object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object]
​ Starting simpliUIListViewsStart.renderedCallback for undefined
​ Get Org Wide Descriptions called successfully - [object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object]
​ Starting simpliUIListViewsStart.renderedCallback for undefined
​ Get List View Descriptions called successfully - [object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object]
​ Starting simpliUIListViewsStart.renderedCallback for undefined
simpli_lv__List_Views_Start:1 Notifications permission has been blocked as the user has ignored the permission prompt several times. This can be reset in Page Info which can be accessed by clicking the lock icon next to the URL. See https://www.chromestatus.com/features/6443143280984064 for more information.
​ Object
​ Object
​ Starting simpliUIListViews.renderedCallback
​ Record id - undefined
​ Starting getListViewConfig - undefined - undefined
​ Current Page Reference...{"type":"standard__navItemPage","attributes":{"apiName":"simpli_lv__List_Views_Example_2"},"state":{}}
​ OBJ Name - simpli_lv__List_Views_Example_2
​ Starting simpliUIListViewsAdminModal.renderedCallback
​ Starting simpliUIListViewsMassCreateModal.renderedCallback for MassCreateModal
​ Starting getListViewShell - undefined - undefined -  - undefined for MassCreateModal
​ Selected list view - undefined for MassCreateModal
​ Starting simpliUIListViews.renderedCallback for Example_2_All_List_View
​ Record id - undefined
​ Spinner ON - renderedCallback - Example_2_All_List_View
​ Component Id created - Example_2_All_List_View:477402
​ Ltn page name        - Example_2_All_List_View for Example_2_All_List_View
​ Page Mode            - App Page for Example_2_All_List_View
​ User config undefined for Example_2_All_List_View
​ Starting simpliUIListViews.renderedCallback for Example_2_All_List_View
​ Record id - undefined
​ Spinner ON - renderedCallback - Example_2_All_List_View
​ Component Id created - Example_2_All_List_View:6180
​ Ltn page name        - Example_2_All_List_View for Example_2_All_List_View
​ Page Mode            - App Page for Example_2_All_List_View
​ User config undefined for Example_2_All_List_View
2​ then
​ Is sys admin called successfully - true for Example_2_All_List_View
​ Component configs retrieved successfully - [object Object] for Example_2_All_List_View
​ Component config size - undefined for Example_2_All_List_View
​ Pinned list view string - undefined
​ There is no pinned list view for Example_2_All_List_View
​ Component configs retrieved successfully - [object Object] for Example_2_All_List_View
​ Component config size - undefined for Example_2_All_List_View
​ Pinned list view string - undefined
​ There is no pinned list view for Example_2_All_List_View
​ User sort configs retrieved successful - {"listviews": []} for Example_2_All_List_View
​ List view sort fields size - 0
​ Starting getObjectsList
​ Finished renderedCallback for Example_2_All_List_View
​ Starting simpliUIListViews.renderedCallback for Example_2_All_List_View
​ Record id - undefined
​ No page initialization needed for Example_2_All_List_View
​ Finished renderedCallback for Example_2_All_List_View
​ User sort configs retrieved successful - {"listviews": []} for Example_2_All_List_View
​ List view sort fields size - 0
​ Starting getObjectsList
​ Finished renderedCallback for Example_2_All_List_View
​ Object list has been populated with size - 1 for Example_2_All_List_View
​ Spinner OFF  - getObjectsList - Example_2_All_List_View
​ Starting simpliUIListViews.renderedCallback for Example_2_All_List_View
​ Record id - undefined
​ No page initialization needed for Example_2_All_List_View
​ Finished renderedCallback for Example_2_All_List_View
​ Object list has been populated with size - 1 for Example_2_All_List_View
​ Spinner OFF  - getObjectsList - Example_2_All_List_View
​ Object
​ Object
​ Popover set for hiding - Example_2_All_List_View
​ Starting simpliUIListViews.renderedCallback for Example_2_All_List_View
​ Record id - undefined
​ No page initialization needed for Example_2_All_List_View
​ Finished renderedCallback for Example_2_All_List_View
​ Spinner ON - handleObjectChange - Example_2_All_List_View
​ Object selected - User for Example_2_All_List_View
simpliUIListViews.js:4 Starting simpliUIListViews.renderedCallback for Example_2_All_List_View
simpliUIListViews.js:4 Record id - undefined
simpliUIListViews.js:4 No page initialization needed for Example_2_All_List_View
simpliUIListViews.js:4 Finished renderedCallback for Example_2_All_List_View
simpliUIListViews.js:4 Object list view retrieval successful for Example_2_All_List_View
simpliUIListViews.js:4 Object list view size - 3 for Example_2_All_List_View
simpliUIListViews.js:4 Pinned list view      - undefined for Example_2_All_List_View
simpliUIListViews.js:4 First List View Get   - true for Example_2_All_List_View
simpliUIListViews.js:4 Spinner OFF  - getListViewsForObject - Example_2_All_List_View
simpliUIListViews.js:4 Starting simpliUIListViews.renderedCallback for Example_2_All_List_View
simpliUIListViews.js:4 Record id - undefined
simpliUIListViews.js:4 No page initialization needed for Example_2_All_List_View
simpliUIListViews.js:4 Finished renderedCallback for Example_2_All_List_View
simpliUIListViews.js:4 Old list view - undefined for Example_2_All_List_View
simpliUIListViews.js:4 Sort data - [object Map] for Example_2_All_List_View
simpliUIListViews.js:4 Spinner ON - handleListViewSelected - Example_2_All_List_View
simpliUIListViews.js:4 New list view - AllUsers for Example_2_All_List_View
simpliUIListViews.js:4 Starting ListView Data Refresh for Example_2_All_List_View
simpliUIListViews.js:4 Spinner ON - getListViewDataPage - Example_2_All_List_View
simpliUIListViewsAdminModal.js:4 Starting getListViewConfig - User - AllUsers
simpliUIListViews.js:4 Starting simpliUIListViews.renderedCallback for Example_2_All_List_View
simpliUIListViews.js:4 Record id - undefined
simpliUIListViews.js:4 No page initialization needed for Example_2_All_List_View
simpliUIListViews.js:4 Finished renderedCallback for Example_2_All_List_View
simpliUIListViewsAdminModal.js:4 List view config retrieval successful
simpliUIListViews.js:4 List view actions retrieval successful for Example_2_All_List_View
simpliUIListViews.js:4 Object action list size - 5
simpliUIListViews.js:4 Starting simpliUIListViews.renderedCallback for Example_2_All_List_View
simpliUIListViews.js:4 Record id - undefined
simpliUIListViews.js:4 No page initialization needed for Example_2_All_List_View
simpliUIListViews.js:4 Finished renderedCallback for Example_2_All_List_View
simpliUIListViewsAdminModal.js:4 List view column label retrieval successful
simpliUIListViews.js:4 Starting refreshListViewData - Example_2_All_List_View - User - AllUsers -  - -1 for Example_2_All_List_View
simpliUIListViews.js:4 XXXXX columnSortDataStr -  for Example_2_All_List_View
simpliUIListViews.js:4 Selected list view - AllUsers for Example_2_All_List_View
simpliUIListViews.js:4 this.listViewData            - undefined for Example_2_All_List_View
simpliUIListViews.js:4 this.listViewData.coreListId - undefined for Example_2_All_List_View
simpliUIListViews.js:4 listViewDataResult undefined for Example_2_All_List_View
simpliUIListViews.js:4 Spinner OFF  - getListViewDataPage - Example_2_All_List_View
simpliUIListViews.js:4 Starting simpliUIListViews.renderedCallback for Example_2_All_List_View
simpliUIListViews.js:4 Record id - undefined
simpliUIListViews.js:4 No page initialization needed for Example_2_All_List_View
simpliUIListViews.js:4 Finished renderedCallback for Example_2_All_List_View
3simpliUIListViews.js:4 Popover set for hiding - Example_2_All_List_View
DevTools failed to load source map: Could not load content for chrome-extension://lnkgcmpjkkkeffambkllliefdpjdklmi/js/angular.min.js.map: HTTP error: status code 404, net::ERR_UNKNOWN_URL_SCHEME
DevTools failed to load source map: Could not load content for chrome-extension://lnkgcmpjkkkeffambkllliefdpjdklmi/js/angular-animate.min.js.map: HTTP error: status code 404, net::ERR_UNKNOWN_URL_SCHEME
DevTools failed to load source map: Could not load content for https://static.lightning.force.com/auraFW/javascript/1633469907294/aura_prod.js.map: HTTP error: status code 503, net::ERR_HTTP_RESPONSE_CODE_FAILURE
DevTools failed to load source map: Could not parse content for https://ea-dev-org-dev-ed.lightning.force.com/javascript/1515605724000/ui-sfdc-javascript-impl/source/RecordGVP.js.map: Unexpected end of JSON input
DevTools failed to load source map: Could not parse content for https://ea-dev-org-dev-ed.lightning.force.com/javascript/1595964957000/canvas/source/CanvasRendering.js.map: Unexpected end of JSON input
DevTools failed to load source map: Could not load content for https://ea-dev-org-dev-ed.lightning.force.com/resource/1639753840000/jspdf.umd.min.js.map: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE`

**Comment by tomansley** [comment] 2021-12-17 16:08
Yea, I wondered if that might happen.

Ok, can you send me the following things - 

1. Screenshot of the components and if possible indicators identifying what each component is. i.e. Single List View, Related etc.
2. Screenshots of the component config when editing the page.

Here is the next release which undoes the changes which broke everything - https://<YOUR_URL>/packaging/installPackage.apexp?p0=04t3h000004pMtg

**Comment by geekyakshay** [comment] 2021-12-17 17:16
@tomansley Here we go next:
Configured a parent list view on the account record page, and it start throwing errors in the console and infinite spinning on the screen. 
![image](https://user-images.githubusercontent.com/33083757/146582518-cbf22c82-e733-4c11-8995-23d9c728d0f4.png)
Configuration Below: 
![image](https://user-images.githubusercontent.com/33083757/146582667-48920b1f-4386-4862-8020-602892691616.png)
![image](https://user-images.githubusercontent.com/33083757/146582699-8d825c72-c7d9-406a-9757-09c7f9f42ad4.png)

**Comment by tomansley** [comment] 2021-12-17 17:40
Akshay,

I think I managed to reproduce your issue. So that is good. Question -

You have a component of type "Single List View" placed in a related list section on a record page right? What exactly is the process you are trying to create? If a user selects an account they go to the account page. What then is the reason for wanting a component of type "Single List View"? Why are you not using the "Related List View" component which automatically gets related records based on the user selected record (in this case the account)

Also, the single list view component looks to be getting other accounts. What accounts are these and how are they associated to the user selected account? If the accounts are related to the user selected account I would think it makes sense to use a Related List View component.

Cheers
Tom

**Comment by geekyakshay** [comment] 2021-12-17 18:17
@tomansley The scenario i demonstrated above is just for re-producing the issue, Actually implementation of SIMPLI on record page is different, I have couple of custom objects which I want to display and filter on account record page. 

Example: I have below components on the account record page:
Action Plan (Child to Account - Custom Object) SIMPLI list view,
Action Plan Tasks (Child to Action Plan - Custom Object) SIMPLI list view.

Good to know you were able to re-produce. Thanks for the quick responses.

**Comment by tomansley** [comment] 2021-12-18 16:53
Akshay,

From what you describe it sounds like the two custom objects that you want
to display are related to the account. If this is the case then you
definitely want to use Related List View component type. This should work
as you would expect. Let me know if it doesn't.

I will continue to try and resolve the issue we have discovered (regarding
the Single List View mode) but think you should be able to move forward now.

Let me know if you believe otherwise.

Cheers
Tom

**Comment by tomansley** [comment] 2021-12-18 16:58
Actually, I looked at your example again and noticed the one object is related not to the account but to the child objects. So you have children of children. This is a very interesting scenario which definitely will need a single list view.

I will try to reproduce this exact scenario and try to resolve.

Thanks for being patient Akshay!! 🙂

**Comment by tomansley** [comment] 2021-12-19 09:09
Akshay,

I believe I have resolved this issue. Please try the following package and let me know how it goes.

https://<YOUR_URL>/packaging/installPackage.apexp?p0=04t3h000004pMtl

Thanks
Tom

**Comment by geekyakshay** [comment] 2021-12-19 11:10
Hi @tomansley Thanks for fixing the issue, I tried installing the version but had no success, Maybe a packaging issue?
![image](https://user-images.githubusercontent.com/33083757/146672819-97f2f6fa-8eb1-4209-8705-dfb2acb63526.png)

**Comment by tomansley** [comment] 2021-12-19 14:53
Apologies Akshay. I included parts of my testing which I believe is the problem.

Try this - https://<YOUR_URL>/packaging/installPackage.apexp?p0=04t3h000004pMtq

**Comment by geekyakshay** [comment] 2021-12-20 08:33
Hi @tomansley 
The component is not producing any results on the Account record page.
![image](https://user-images.githubusercontent.com/33083757/146736765-0c35d6f5-8c12-45b7-a16e-406af0f95a8f.png)
![image](https://user-images.githubusercontent.com/33083757/146736790-3e9c61a8-c2c6-4c3c-bc96-cc4d81be9d87.png)

Note: Yes, I have data in the system. List view query is also valid..

**Comment by tomansley** [comment] 2021-12-20 14:20
Hi Akshay,

I have created a video to go over what I believe is the scenario you were trying to resolve for. I created the video because this is a slightly more complicated scenario than usual

https://youtu.be/gJR48o_HDis (give it 5-10 min to finish uploading and processing)

Let me know your thoughts on this as right now I am a bit confused as to why things are not working.

Cheers
Tom

**Comment by geekyakshay** [comment] 2021-12-20 18:38
Hi @tomansley, 

Thanks a lot for the demonstration video, appreciate getting your immediate attention on this issue. 
After re-configuration with a different set of Parent-Child object relations, I confirm that the functionality is working fine without any exception message, Plus the Children of Children's records are getting captured in a correct hierarchy. 

This is a great tool and I think it has got a lot of potentials. :)

**Comment by tomansley** [comment] 2021-12-20 18:41
Yae!!

That is awesome news. I'll schedule this bug fix for a full release. Thank
you so much Akshay!

**Comment by alesiadvorkina** [comment] 2021-12-21 01:49
This is fantastic! Thank you so much for the quick attention to this @tomansley ! (I am working with Akshay :)) When can we expect a new release, just so we can set expectations with the business?

**Comment by tomansley** [comment] 2021-12-21 02:48
It should be available by the end of the week.

**Comment by tomansley** [comment] 2021-12-22 20:46
Released in v2.92

**Closed by tomansley** 2021-12-22 20:46 UTC
Labels: bug, ready for release
