### ISSUE TITLE
simpliUIListViews component no longer returning records for certain objects

### ISSUE THREAD

**Issue by arozebo2** [tomansley/SimpliListViews#146] opened 2023-04-15 02:41 UTC
**Describe the bug**
Created a new App Page and added the SimpliUIListViews component 3 times. One component for 3 separate objects.
For 2 of the objects, list views are appearing as expected, but the records within the list views do not return.
For the 3rd object, list views are appearing as expected, and the records within the list views do return.
 
**Simpli List View Version**
2.150

**To Reproduce**
1. Create new App Page.
2. Add component "SimpliUIListViews' and set component mode = 'Single List View'. Populate Single List View Object = 'CustomObject1__c'
3. Add component 'SimpliUIListViews' and set component mode = 'Single List View'. Populate Single List View Object = 'CustoObject2__c'
4. Save and activate
5. Go to App Page
6. Results return for CustomObject1__c. 
7. For CustomObject2__c, message displays "No rows available to be displayed."
8. Click 'Go to the original SFDC list view' button
9. List view opens in standard tab with 50+ records returned.

**Expected behavior**
Records for CustomObject2__c are expected to appear. This is not consistent behavior between sandbox and production. In Sandbox, the same exact objects are used, and behavior is expected. When we went to install in Production, the results are as above and have halted our production deployment. 

**Screenshots**
![image](https://user-images.githubusercontent.com/130811610/232179295-1a856132-4be9-4208-a56c-587e1d4a4c2c.png)
![image](https://user-images.githubusercontent.com/130811610/232179308-aff0e403-b941-4a3e-bc3f-360294cefe37.png)

**Desktop (please complete the following information):**
 - Browser: Chrome
 - 
**Additional context**
1. Was working in sandbox with exact intended behavior
2. Not working in production 
3. I've uninstalled the app from production, reinstalled and still have the same issue.
4. I have create new list views for the custom object, refreshed list views, tried to copy/paste the raw list view details from sandbox to production, and nothing works. I'm working with 2 custom objects and 1 standard (Product2). All objects work in sandbox. In Production, 1 custom object works, 1 custom object and the standard object do not work.

**Comment by tomansley** [comment] 2023-04-15 03:49
Hello,

Did you set the 'Joined Field Name' for the list views. This config setting is towards the bottom of the settings. These must be set correctly otherwise the data will not show.

Thanks
Tom
________________________________
From: arozeperrigo ***@***.***>
Sent: Saturday, April 15, 2023 4:41:17 AM
To: tomansley/SimpliListViews ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [tomansley/SimpliListViews] simpliUIListViews component no longer returning records for certain objects (Issue #146)


Describe the bug
Created a new App Page and added the SimpliUIListViews component 3 times. One component for 3 separate objects.
For 2 of the objects, list views are appearing as expected, but the records within the list views do not return.
For the 3rd object, list views are appearing as expected, and the records within the list views do return.

Simpli List View Version
2.150

To Reproduce
Steps to reproduce the behavior:

  1.  Create new App Page.
  2.  Add component "SimpliUIListViews' and set component mode = 'Single List View'. Populate Single List View Object = 'CustomObject1__c'
  3.  Add component 'SimpliUIListViews' and set component mode = 'Single List View'. Populate Single List View Object = 'CustoObject2__c'
  4.  Save and activate
  5.  Go to App Page
  6.  Results return for CustomObject1__c.
  7.  For CustomObject2__c, message displays "No rows available to be displayed."
  8.  Click 'Go to the original SFDC list view' button
  9.  List view opens in standard tab with 50+ records returned.

Expected behavior
Records for CustomObject2__c are expected to appear. This is not consistent behavior between sandbox and production. In Sandbox, the same exact objects are used, and behavior is expected. When we went to install in Production, the results are as above and have halted our production deployment.

Screenshots
[image]<https://user-images.githubusercontent.com/130811610/232179195-33d7afd2-6023-44d8-b00e-3e8b753a0c9c.png>
[image]<https://user-images.githubusercontent.com/130811610/232179207-6a633e01-4af0-4f9c-a11a-27e976122b6a.png>

Desktop (please complete the following information):

  *   Browser: Chrome
  *

Additional context

  1.  Was working in sandbox with exact intended behavior
  2.  Not working in production
  3.  I've uninstalled the app from production, reinstalled and still have the same issue.
  4.  I have create new list views for the custom object, refreshed list views, tried to copy/paste the raw list view details from sandbox to production, and nothing works. I'm working with 2 custom objects and 1 standard (Product2). All objects work in sandbox. In Production, 1 custom object works, 1 custom object and the standard object do not work.

**Comment by tomansley** [comment] 2023-04-15 07:29
Also, there is an FAQ page that might assist. Especially this item - https://github.com/tomansley/SimpliListViews/wiki/FAQ#i-have-two-list-views-on-the-page-to-allow-for-filtering-but-when-i-select-records-from-one-the-other-does-not-filter-based-on-the-selection-1
________________________________
From: arozeperrigo ***@***.***>
Sent: Saturday, April 15, 2023 4:41:17 AM
To: tomansley/SimpliListViews ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [tomansley/SimpliListViews] simpliUIListViews component no longer returning records for certain objects (Issue #146)


Describe the bug
Created a new App Page and added the SimpliUIListViews component 3 times. One component for 3 separate objects.
For 2 of the objects, list views are appearing as expected, but the records within the list views do not return.
For the 3rd object, list views are appearing as expected, and the records within the list views do return.

Simpli List View Version
2.150

To Reproduce
Steps to reproduce the behavior:

  1.  Create new App Page.
  2.  Add component "SimpliUIListViews' and set component mode = 'Single List View'. Populate Single List View Object = 'CustomObject1__c'
  3.  Add component 'SimpliUIListViews' and set component mode = 'Single List View'. Populate Single List View Object = 'CustoObject2__c'
  4.  Save and activate
  5.  Go to App Page
  6.  Results return for CustomObject1__c.
  7.  For CustomObject2__c, message displays "No rows available to be displayed."
  8.  Click 'Go to the original SFDC list view' button
  9.  List view opens in standard tab with 50+ records returned.

Expected behavior
Records for CustomObject2__c are expected to appear. This is not consistent behavior between sandbox and production. In Sandbox, the same exact objects are used, and behavior is expected. When we went to install in Production, the results are as above and have halted our production deployment.

Screenshots
[image]<https://user-images.githubusercontent.com/130811610/232179195-33d7afd2-6023-44d8-b00e-3e8b753a0c9c.png>
[image]<https://user-images.githubusercontent.com/130811610/232179207-6a633e01-4af0-4f9c-a11a-27e976122b6a.png>

Desktop (please complete the following information):

  *   Browser: Chrome
  *

Additional context

  1.  Was working in sandbox with exact intended behavior
  2.  Not working in production
  3.  I've uninstalled the app from production, reinstalled and still have the same issue.
  4.  I have create new list views for the custom object, refreshed list views, tried to copy/paste the raw list view details from sandbox to production, and nothing works. I'm working with 2 custom objects and 1 standard (Product2). All objects work in sandbox. In Production, 1 custom object works, 1 custom object and the standard object do not work.

**Comment by arozebo2** [comment] 2023-04-15 10:30
I don’t have it set in sandbox for 1 of the custom objects where data is not appearing, because it is the driving object. Is there a reason I need it in prod if it is the “parent”?

Alicia Rozeboom | Salesforce Product Owner
Office: (269) 686-3342

**Comment by tomansley** [comment] 2023-07-08 03:47
Hello,

I have recently discovered a bug which might have been causing the issues
you were experiencing. I am almost finished resolving the issue and will
send you a link to the new package for testing.

I should have the new package to you in a couple of days.

Cheers
Tom

**Comment by arozebo2** [comment] 2023-07-10 12:22
Thank you for the update!

Alicia Rozeboom | Salesforce Product Owner
Office: (269) 686-3342

**Comment by tomansley** [comment] 2023-07-12 17:25
Issue resolved in v2.155

**Closed by tomansley** 2023-07-12 17:25 UTC
